name = "AquaSkyLES"
uuid = "660aa2fb-d4c8-4359-a52c-9c057bc511da"
authors = ["Navid C. Constantinou <navidcy@users.noreply.github.com>, Madi, Greg, Marty, Callum, and Paul"]
version = "0.1.0"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
AtmosphericProfilesLibrary = "86bc3604-9858-485a-bdbe-831ec50de11d"
CloudMicrophysics = "6a9e3e04-43cd-43ba-94b9-e8782df3c71b"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
RootSolvers = "7181ea78-2dcb-4de3-ab41-2b8ab5a31e74"

[compat]
Adapt = "4.3.0"
CloudMicrophysics = "0.22.13"
JLD2 = "0.5.13"
Oceananigans = "0.96.29"
RootSolvers = "0.4.4"
